### ISSUE TITLE
`dist/` should not be deleted win rebuilds, only contents instead

### ISSUE THREAD

**Issue by filipesilva** [jvandemo/generator-angular2-library#91]
@jvandemo heya, I recently discovered a [shortcoming in my starter](https://github.com/filipesilva/angular-quickstart-lib/commit/ce13ea3ee5a962e5c46edeef7678e8339265a74d), where the `dist/` dir is always deleted.

This causes linked libraries to not update the project that are using it, since the link is broken when `dist/` is deleted. Instead, only it's contents should be deleted.

Details and repro can be found at https://github.com/angular/angular-cli/issues/6195.

**Comment by filipesilva** [comment]
Update: removing `clean:dist' from line 173 and 182 is actually necessary to fully get refreshes to work. This isn't ideal. Discussion ongoing in angular/angular-cli#6195.

**Comment by jvandemo** [comment]
@filipesilva &mdash; Thank you for your note, much appreciated! 👍 

I will have a look at this tomorrow morning before work and will keep you posted. Thanks again!

**Comment by jvandemo** [comment]
Just fo confirm that I am seeing the same behavior here (on Mac).

Setup:

1. generate library using [generator-angular2-library](https://github.com/jvandemo/generator-angular2-library) in directory `my-lib`
2. in `my-lib`, run `gulp` to build `my-lib/dist`
3. in `my-lib/dist`, run `npm link`
4. generate app with Angular CLI in `my-app`
5. in `my-app`, run `npm link my-lib`
6. import `my-lib` in `app.module.ts`
7. in `my-app`, run `ng serve --aot`

Scenario:

1. change file in `my-lib/src`
2. gulp will pick up change and regenerate `my-lib/dist`
3. `ng-serve --aot` detects a change and recompiles successfully
4. the web page does not reflect the change

Learnings so far:

1. files in `my-app/node_modules` update correctly
2. angular-cli does seem to detect the change and runs a compilation, but the output does not reflect the change
3. running `ng serve` instead of `ng serve --aot` shows the change correctly

I will perform some additional research before work later this week 👍 

[Watch recording to see it happening live on screen](https://www.dropbox.com/s/ebdkqc2m5bdrp30/2017-05-18-refresh-issue.gif?dl=0)

**Comment by bniedermeyer** [comment]
It looks like the refresh issue with Angular CLI still isn't figured out, but I've made a change to my local instance of the gulp file and got clean to work without unlinking `dist/` using [the steps outlined here.](https://www.npmjs.com/package/del#beware) I'd be happy to do a quick PR if you'd like.

**Comment by clarkj** [comment]
@bniedermeyer I'm running into this same issue-would you mind posting your gulp file, as I'm struggling to find where I should be making these changes.  Thanks!

**Comment by bniedermeyer** [comment]
@clarkj Sure thing. I made a modification to `deleteFolders()`. I posted a Gist [here](https://gist.github.com/bniedermeyer/1dd887244bdd31b6dc3bc8534c4c555d). Because using del, deletes the folder itself, you just have to set it to ignore.

**Comment by jvandemo** [comment]
I have just released v10.2.2, which no longer deletes the `dist` directory.

@filipesilva and @bniedermeyer &mdash; Thank you for your help! Much appreciated! 👍 

I will leave this issue open to further investigate the refresh issue.

**Comment by sgentile** [comment]
now I get the error

```
RROR in ../ng-library/dist/index.js
Module build failed: Error: ENOENT: no such file or direc
tory, open '.../ng-library/dist/index.js'
 @ ./src/app/app.module.ts 10:0-53
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200
./src/main.ts
webpack: Failed to compile.
```

**Comment by sgunapude** [comment]
The workaround around i am using is to comment out the code in clean:dist task

**Comment by jvandemo** [comment]
@sgentile &mdash; Are you still getting this error with the latest version of the generator? Thanks!

**Comment by sgunapude** [comment]
@jvandemo i tested it today with the latest generator and the missing index.js error still happens.

**Comment by ljacques** [comment]
the problem persists when the components are in subdirectories in the library

**Comment by sgentile** [comment]
yes, because the app linking to it fails because index.js doesn't exist any
longer...  (the host is using angular-cli and in watch mode, as soon as it
rebuilds it fails, and then exits).

ie.

ERROR in ../library/dist/index.js
Module build failed: Error: ENOENT: no such file or directory, open
'.../Projects/library/dist/index.js'
    at Error (native)
 @ ./src/app/app.module.ts 29:0-53
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts


my workaround has been to link to src during development and then just
validate aot, tests before pushing my code by then linking to dist.

**Comment by sambaptista** [comment]
Due the the [more strict cli 1.5](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced#148d),  When I link from /src in my library, I get the following error in the app that consumes my library: 

Module build failed: Error: .../src/index.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

Does it mean that I have to add files in tsconfig manually (and not to forget to remove it further), or is there a better practice ?

**Comment by txinfo** [comment]
@sgentile Since the Angular 5.x changes mentioned by @sambaptista ,the linking to src method no longer works cleanly. I can only find a reliable workaround by hard linking the library code into the consuming app's source tree which is less than ideal and adding a path ref to the tsconfig.app.json. Have you find any other solutions?

Linking to /src was so quick and painless. gulp watching the lib breaks execution frequently (e.g. on error, missing index.js error) and takes longer as it has to compile fully each time.
